language: scala
scala:
  - 2.12.1

jdk:
  - oraclejdk8

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage testOnly Chatastrophe.tests.ServerTest coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: eckerddevelopers:5F0xCSx0NtjfoJzQSojDKfnK

# blocklist
branches:
  except:
  - fixServerStoppingOnClientJoin
  - master

# safelist
branches:
  only:
  - refactoring